In [11]:
# pip install pandas 
# !pip install openpyxl

In [5]:
import pandas as pd

In [6]:
data = pd.read_excel("C:/Users/wwwde/OneDrive - Florida Atlantic University/Academics/Research/NDHS/Dataset/Children's Recode/Children Recode.xlsx")
data.head()

,caseid,bidx,v000,v001,v002,v003,v004,v005,v006,v007,...,s604c,s607ea,s607eb,s607ec,s607ed,s607ex,s607f,s607g,s615f,s631o
0,1 1 2,1,NP8,1,1,2,1,916093,10,2078,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1,1 8 2,1,NP8,1,8,2,1,916093,10,2078,...,0.0,0.0,1.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
2,1 8 2,2,NP8,1,8,2,1,916093,10,2078,...,NaN,0.0,1.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0
3,1 9 3,1,NP8,1,9,3,1,916093,10,2078,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0
4,1 19 1,1,NP8,1,19,1,1,916093,10,2078,...,0.0,1.0,1.0,0.0,0.0,0.0,NaN,0.0,NaN,NaN

In [19]:
df1 = data.copy()
df1 = df1[['b19', 'v106', 'v190', 'v102', 'v101', 'v445', 'b11', 'v137', 'v130', 'v131', 'm19', 'b4', 'm4', 'v012', 'v729', 'v714', 'v481', 'hw71']]
df1.head()

,b19,v106,v190,v102,v101,v445,b11,v137,v130,v131,m19,b4,m4,v012,v729,v714,v481,hw71
0,41,1,1,2,1,NaN,36.0,1,4,8,NaN,2,NaN,29,2.0,1,0,NaN
1,28,1,1,2,1,NaN,13.0,2,1,2,9996.0,2,95.0,33,1.0,0,0,NaN
2,42,1,1,2,1,NaN,NaN,2,1,2,NaN,2,NaN,33,1.0,0,0,NaN
3,17,1,1,2,1,2200.0,207.0,1,1,2,3100.0,2,95.0,34,3.0,0,0,-65.0
4,40,2,2,2,1,2510.0,19.0,2,4,8,NaN,1,NaN,26,2.0,1,0,-185.0

In [27]:
df1.rename(columns={'b19': 'Child_age', 'v106':'Mother_education', 'v190':'Wealth_index', 'v102':'Place_residence', 'v101':'Region', 'v445':'BMI', 'b11':'Birth_interval', 'v137':'Children_under5', 'v130':'Religion', 'v131':'Ethnicity', 'm19':'Birth_weight', 'b4':'Child_sex', 'm4':'Breastfeeding_duration', 'v012':'Mother_age', 'v729':'Father_education', 'v714':'Mother_working', 'v481':'Health_insurance', 'hw71':'Status'}, inplace=True)
df1.head()

,Child_age,Mother_education,Wealth_index,Place_residence,Region,BMI,Birth_interval,Children_under5,Religion,Ethnicity,Birth_weight,Child_sex,Breastfeeding_duration,Mother_age,Father_education,Mother_working,Health_insurance,Status
0,41,1,1,2,1,NaN,36.0,1,4,8,NaN,2,NaN,29,2.0,1,0,NaN
1,28,1,1,2,1,NaN,13.0,2,1,2,9996.0,2,95.0,33,1.0,0,0,NaN
2,42,1,1,2,1,NaN,NaN,2,1,2,NaN,2,NaN,33,1.0,0,0,NaN
3,17,1,1,2,1,2200.0,207.0,1,1,2,3100.0,2,95.0,34,3.0,0,0,-65.0
4,40,2,2,2,1,2510.0,19.0,2,4,8,NaN,1,NaN,26,2.0,1,0,-185.0