In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [27]:
df_original = pd.read_csv('Children Recode_final.csv')
columns = ['Underweight', 'Stunting', 'Wasting'] + [col for col in df_original.columns if col!= 'Wasting']
df1 = df_original[columns]
df1.head()

,Underweight,Stunting,Wasting,Child_age,Mother_education,Age_first_sex,Pregnancy_terminated,Wealth_index,Place_residence,BMI,...,Religion_5,Ethnicity_2,Ethnicity_3,Ethnicity_4,Ethnicity_5,Ethnicity_6,Ethnicity_7,Ethnicity_8,Ethnicity_9,Ethnicity_10
0,0,0,0,17,1,14.0,0,1,2,22.00,...,0,1,0,0,0,0,0,0,0,0
1,0,1,0,40,2,17.0,1,2,2,25.10,...,0,0,0,0,0,0,0,1,0,0
2,0,1,0,59,2,17.0,1,2,2,25.10,...,0,0,0,0,0,0,0,1,0,0
3,1,1,0,55,2,17.0,0,2,2,21.53,...,0,0,0,0,0,0,0,1,0,0
4,0,0,0,14,1,16.0,0,1,2,28.03,...,0,0,0,0,0,0,0,1,0,0

## Stunting Prediction

In [36]:
df2 = df1.drop(['Underweight', 'Wasting'], axis = 1)
df2.head()

,Stunting,Child_age,Mother_education,Age_first_sex,Pregnancy_terminated,Wealth_index,Place_residence,BMI,Children_under5,Total_children_ever_born,...,Religion_5,Ethnicity_2,Ethnicity_3,Ethnicity_4,Ethnicity_5,Ethnicity_6,Ethnicity_7,Ethnicity_8,Ethnicity_9,Ethnicity_10
0,0,17,1,14.0,0,1,2,22.00,1,1,...,0,1,0,0,0,0,0,0,0,0
1,1,40,2,17.0,1,2,2,25.10,2,2,...,0,0,0,0,0,0,0,1,0,0
2,1,59,2,17.0,1,2,2,25.10,2,2,...,0,0,0,0,0,0,0,1,0,0
3,1,55,2,17.0,0,2,2,21.53,1,1,...,0,0,0,0,0,0,0,1,0,0
4,0,14,1,16.0,0,1,2,28.03,1,1,...,0,0,0,0,0,0,0,1,0,0