In [1]:
import pyreadstat

In [15]:
df_bh = pyreadstat.read_sav('/workspaces/malnutrition/MICS/bh.sav')[0]
df_hh = pyreadstat.read_sav('/workspaces/malnutrition/MICS/hh.sav')[0]
df_wm = pyreadstat.read_sav('/workspaces/malnutrition/MICS/wm.sav')[0]
df_ch = pyreadstat.read_sav('/workspaces/malnutrition/MICS/ch.sav')[0]
df_fs = pyreadstat.read_sav('/workspaces/malnutrition/MICS/fs.sav')[0]
df_mn = pyreadstat.read_sav('/workspaces/malnutrition/MICS/mn.sav')[0]
df_hl = pyreadstat.read_sav('/workspaces/malnutrition/MICS/hl.sav')[0]

# df_ch, meta = pyreadstat.read_sav('/workspaces/malnutrition/MICS/ch.sav')

In [16]:
# df_bh.to_csv('/workspaces/malnutrition/MICS/df_ch.csv', index=False)

In [17]:
print(df_hl.shape)
print(df_bh.shape)
print(df_wm.shape)
print(df_hh.shape)
print(df_fs.shape)
print(df_ch.shape)
print(df_mn.shape)

(56595, 84)
(27345, 53)
(15019, 414)
(12800, 471)
(7824, 254)
(6749, 449)
(5605, 199)

In [18]:
df1 = df_ch[['BD2', 'UB9', 'CA1', 'CA14', 'AN4', 'AN8', 'HH6', 'HL4', 'melevel1', 'cinsurance', 'HH7c', 'windex5', 'WAZ2', 'HAZ2', 'WHZ2']]
df1.head()

,BD2,UB9,CA1,CA14,AN4,AN8,HH6,HL4,melevel1,cinsurance,HH7c,windex5,WAZ2,HAZ2,WHZ2
0,1.0,2.0,2.0,2.0,1.0,7.8,2.0,1.0,5.0,2.0,1.0,1.0,-2.94,-3.53,-1.69
1,NaN,2.0,2.0,1.0,3.0,12.5,2.0,1.0,5.0,2.0,1.0,1.0,-1.93,-2.58,-0.65
2,1.0,2.0,1.0,2.0,2.0,11.1,2.0,2.0,2.0,2.0,1.0,1.0,-1.45,-1.07,-1.27
3,1.0,2.0,1.0,1.0,1.0,9.3,2.0,2.0,2.0,2.0,1.0,1.0,-0.98,-0.90,-0.74
4,NaN,2.0,2.0,2.0,4.0,14.7,2.0,2.0,2.0,2.0,1.0,1.0,-1.35,-1.67,-0.45

In [19]:
df2 = df1.rename(columns={
    'AN4': 'child_age',
    'AN8': 'child_weight',
    'BD2': 'ever_breastfed',
    'UB9': 'insurance',
    'CA1': 'diarrhoea_last_2_weeks',
    'CA14': 'fever_last_2_weeks',
    'HH6': 'area',
    'HL4': 'child_sex',
    'melevel1': 'mother_education',
    'cinsurance': 'health_insurance',
    'HH7c': 'province',
    'windex5': 'wealth_index',
    'WAZ2': 'underweight',
    'HAZ2': 'stunting',
    'WHZ2': 'wasting'
})
df2.head()

,ever_breastfed,insurance,diarrhoea_last_2_weeks,fever_last_2_weeks,child_age,child_weight,area,child_sex,mother_education,health_insurance,province,wealth_index,underweight,stunting,wasting
0,1.0,2.0,2.0,2.0,1.0,7.8,2.0,1.0,5.0,2.0,1.0,1.0,-2.94,-3.53,-1.69
1,NaN,2.0,2.0,1.0,3.0,12.5,2.0,1.0,5.0,2.0,1.0,1.0,-1.93,-2.58,-0.65
2,1.0,2.0,1.0,2.0,2.0,11.1,2.0,2.0,2.0,2.0,1.0,1.0,-1.45,-1.07,-1.27
3,1.0,2.0,1.0,1.0,1.0,9.3,2.0,2.0,2.0,2.0,1.0,1.0,-0.98,-0.90,-0.74
4,NaN,2.0,2.0,2.0,4.0,14.7,2.0,2.0,2.0,2.0,1.0,1.0,-1.35,-1.67,-0.45

In [22]:
df3 = df2.dropna()
df3.shape

(3760, 15)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6749 entries, 0 to 6748
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   BD2         3760 non-null   float64
 1   UB9         6658 non-null   float64
 2   CA1         6658 non-null   float64
 3   CA14        6658 non-null   float64
 4   AN4         6658 non-null   float64
 5   AN8         6658 non-null   float64
 6   HH6         6749 non-null   float64
 7   HL4         6749 non-null   float64
 8   melevel1    6658 non-null   float64
 9   cinsurance  6658 non-null   float64
 10  HH7c        6749 non-null   float64
 11  windex5     6749 non-null   float64
 12  WAZ2        6658 non-null   float64
 13  HAZ2        6658 non-null   float64
 14  WHZ2        6658 non-null   float64
dtypes: float64(15)
memory usage: 791.0 KB

In [64]:
df.shape

(6749, 15)

In [53]:
df.isnull().sum()

BD2           2989
UB9             91
CA1             91
CA14            91
AN4             91
AN8             91
HH6              0
HL4              0
melevel1        91
cinsurance      91
HH7c             0
windex5          0
WAZ2            91
HAZ2            91
WHZ2            91
dtype: int64

In [ ]:
# df1, meta = pyreadstat.read_sav('C:/Users/dbastola2022/OneDrive - Florida Atlantic University/Academics/Research/Malnutrition/MICS/fs.sav')
# df1.head()

In [60]:
# for var_name, var_label in zip(meta.column_names, meta.column_labels):
#     print(f"{var_name}: {var_label}")